//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Croquis_.NET_Framework_.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Croquis_.NET_Framework_.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ascending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CBItemAscending {
            get {
                return ResourceManager.GetString("CBItemAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Descending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CBItemDescending {
            get {
                return ResourceManager.GetString("CBItemDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First In First Out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CBItemFIFO {
            get {
                return ResourceManager.GetString("CBItemFIFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last In First Out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CBItemLIFO {
            get {
                return ResourceManager.GetString("CBItemLIFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Random に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CBItemRandom {
            get {
                return ResourceManager.GetString("CBItemRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon icon255x255 {
            get {
                object obj = ResourceManager.GetObject("icon255x255", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   15s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu15s {
            get {
                return ResourceManager.GetString("Menu15s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3min に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu180s {
            get {
                return ResourceManager.GetString("Menu180s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   5min に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu300s {
            get {
                return ResourceManager.GetString("Menu300s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   30s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu30s {
            get {
                return ResourceManager.GetString("Menu30s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   10min に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu600s {
            get {
                return ResourceManager.GetString("Menu600s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   60s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu60s {
            get {
                return ResourceManager.GetString("Menu60s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   15min に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu900s {
            get {
                return ResourceManager.GetString("Menu900s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   90s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu90s {
            get {
                return ResourceManager.GetString("Menu90s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   backgroundColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuBackgroundColor {
            get {
                return ResourceManager.GetString("MenuBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Black に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuBlack {
            get {
                return ResourceManager.GetString("MenuBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FullScreen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFullScreen {
            get {
                return ResourceManager.GetString("MenuFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate random numbers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuGenerateRandomNum {
            get {
                return ResourceManager.GetString("MenuGenerateRandomNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GrayScale に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuGrayScale {
            get {
                return ResourceManager.GetString("MenuGrayScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuGrid {
            get {
                return ResourceManager.GetString("MenuGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Interval に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuInterval {
            get {
                return ResourceManager.GetString("MenuInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ListView に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuListview {
            get {
                return ResourceManager.GetString("MenuListview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pause/Resume に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuPauseResume {
            get {
                return ResourceManager.GetString("MenuPauseResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PreparationTime に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuPreparationTime {
            get {
                return ResourceManager.GetString("MenuPreparationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ProgressBar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuProgress {
            get {
                return ResourceManager.GetString("MenuProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuQuit {
            get {
                return ResourceManager.GetString("MenuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuRepeat {
            get {
                return ResourceManager.GetString("MenuRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuReset {
            get {
                return ResourceManager.GetString("MenuReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuStatus {
            get {
                return ResourceManager.GetString("MenuStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   White に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuWhite {
            get {
                return ResourceManager.GetString("MenuWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ScrollIntoView に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ScrollIntoView {
            get {
                return ResourceManager.GetString("ScrollIntoView", resourceCulture);
            }
        }
    }
}
